Add new directives to cluster_submission page
glotzerlab/signac-docs pull request #134
Opened 2021-05-22 20:08 UTC by kidrahahjo

## Description
Newly added directives were updated in the API docs but not in the cluster submission page, this PR adds all supported directives to the cluster submission page.

## Motivation and Context

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-docs/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-docs/blob/master/ContributorAgreement.md).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-docs/blob/master/CONTRIBUTING.md#code-style) of this project.

2021-05-24 16:39 UTC, klywang commented
Looks good. Just out of curiosity though -- why was the `ngpu` moved in the edit?

2021-05-26 02:58 UTC, vyasr approved these changes
LGTM, thanks! I had one question but it's not a blocker. @klywang feel free to merge when you've reviewed and are happy.

2021-05-26 02:58 UTC, vyasr commented on docs/source/cluster_submission.rst
> +
Is there a reason that you moved `executable` down?

2021-05-26 02:59 UTC, vyasr commented
@klywang @kidrahahjo I didn't see Kelly's review when I reviewed. It seems that both of our questions are related to ordering. Perhaps just alphabetize the glossary and then we can call it good?

2021-05-26 12:51 UTC, klywang approved these changes

2021-06-03 01:41 UTC, klywang commented
@kidrahahjo Would you want to alphabetize the glossary before I merge this?

2021-06-03 09:45 UTC, kidrahahjo commented
Sorry, I missed the comments. The reason I changed the order is to maintain consistency between the order mentioned in the [API reference docs](https://docs.signac.io/projects/flow/en/latest/api.html#flow-directives) and this.

I will alphabetize the glossary.

2021-06-03 19:04 UTC, vyasr requested changes
@kidrahahjo that's a good point, but I think the solution there is to also resort the API docs page that you linked. Could you do that as well so that the two lists match?

2021-06-06 14:01 UTC, kidrahahjo commented
@vyasr yes, I'll do it today. I believe it is not a blocker for this PR to get merged?

2021-06-09 16:21 UTC, bdice commented on docs/source/cluster_submission.rst
> +      The fork directive can be set to True to enforce that a particular operation is always executed within a subprocess and not within the Python interpreter’s process even if there are no other re
```suggestion
      The fork directive can be set to True to enforce that a particular operation is always executed within a subprocess and not within the Python interpreter's process even if there are no other reasons that would prevent that.
```

2021-06-09 16:33 UTC, bdice commented
@kidrahahjo @vyasr @klywang I created a PR to re-sort the directives list. I think this PR should be good to go once reviewers have approved. https://github.com/glotzerlab/signac-flow/pull/535

2021-06-09 17:21 UTC, vyasr approved these changes

2021-06-09 17:21 UTC, merged