Fixes for signac 2
glotzerlab/signac-docs pull request #197
Opened 2024-01-03 15:23 UTC by cbkerr

## Description

I did a pass for common fixes going to signac 2.
In addition, query arguments passed in JSON must be lowercase, so I fixed this in the documentation.

## Motivation and Context

Resolves: #192 

## Checklist:

- [X] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-docs/blob/main/CONTRIBUTING.md).
- [X] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-docs/blob/main/ContributorAgreement.md).
- [X] My code follows the [code style guideline](https://github.com/glotzerlab/signac-docs/blob/main/CONTRIBUTING.md#code-style) of this project.

2024-01-09 15:39 UTC, b-butler requested changes
We need to revert the Boolean changes and mention that the command line interface expects JSON while the Python interface requires valid Python.

It is confusing for users, but it's better to explain it this way to avoid errors on one interface or the other.

2024-01-24 22:11 UTC, cbkerr reviewed
I agree we should clarify that the python interface still needs proper True and False and clarify when we are in each one

The table at the end is only for CLI. I think we need to add a column to the table for Python and CLI

Here is some terminal output showing what works on the CLI.

Setup:
```bash
$ signac init
Initialized project.
$ signac job -c '{"a":1}'
42b7b4f2921788ea14dac5566e6f06d0
$ signac job -c '{"b":2}'
a1ad2ae30a5e8cc1ecb9663235105278
```
Note what it interprets arguments as:
```bash
$ signac find a 1
Interpreted filter arguments as '{"a": 1}'.
42b7b4f2921788ea14dac5566e6f06d0
```

Exactly pasted as in documentation now
```bash
$ signac find {'a': {'$exists': True}}
Interpreted filter arguments as '{"{a:": "{$exists:", "True}}": {"$exists": true}}'.
```

Try to amend with double quotes on the outside
```bash
$ signac find "{'a': {'$exists': True}}"
Failed to parse query argument. Ensure that '{'a': {'': True}}' is valid JSON!
Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

Swap double and single quotes
```bash
$ signac find '{"a": {"$exists": True}}'
Failed to parse query argument. Ensure that '{"a": {"$exists": True}}' is valid JSON!
Error: Expecting value: line 1 column 19 (char 18)
```

Use JSON true instead of Python True
```bash
(py310) Quince:signac-query Corwin$ signac find '{"a": {"$exists": true}}'
42b7b4f2921788ea14dac5566e6f06d0
```

This matches what signac spits out "interpreted filter argments as"
```bash
$ signac find a
Interpreted filter arguments as '{"a": {"$exists": true}}'.
42b7b4f2921788ea14dac5566e6f06d0
```

2024-01-24 22:11 UTC, cbkerr commented on docs/source/query.rst
> +Likewise, using ``false`` as argument would return all documents that have no key with the given name.
I think the confusion is what on this page refers to CLI vs Python.

2024-01-24 22:11 UTC, cbkerr commented on docs/source/query.rst
> +If you provide an odd number of arguments, the last value will default to ``{'$exists': true}``.
This code is in the section "Simplified Syntax on the Comand Line" so I expected it to work on the CLI

2024-01-25 21:56 UTC, melodyyzh approved these changes
Talked to @cbkerr in person, looks good to me

2024-01-26 21:29 UTC, merged